name: WoodChoppingTrials
version: 0.0.0
author: EquaFerrous
main: me.equaferrous.woodchoppingtrials.Main
api-version: 1.19
description: Provides the functionality for the Wood Chopping Trials minigame.
commands:
  createTree:
    description: Places a new tree.
    usage: /<command> (one | two | ... | ten)
  removeTree:
    description: Removes a tree.
    usage: /<command>
permissions:
  gameMaster:
    description: Gives access to all commands to change and run the game.
    default: op
    children:
      gameAdmin: true
  gameAdmin:
    description: Gives access to commands to assist with running the game.
    default: false
